version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo CI install started on `date`
      - npm ci
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - echo Build started on `date`
      - npm run clean
      - npm run build
      - echo Build completed on `date`
  post_build:
    commands:
      - aws s3 sync ./public s3://alexkearns.co.uk --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"